### PR TITLE
244 pork animations

### LINKED ISSUE #244: Pork Animations

### PR DESCRIPTION
**Pull request by wilberquito**
closes #244

### CODE REVIEW

**Comment by Jumalita** [comment]
Very good job @wilberquito!

I only miss a land animation... If you notice, the final posture when jumping, is too diferent from idle position. A  land animation will solve that or maybe make the end of jump animation with a posture more alike idle one. 

And also.... maybe idle animation is too exagerated... I think you should go for something more "calm".

**Comment by wilberquito** [comment]
> Very good job @wilberquito!
> 
> 
> 
> I only miss a land animation... If you notice, the final posture when jumping, is too diferent from idle position. A  land animation will solve that or maybe make the end of jump animation with a posture more alike idle one. 
> 
> 
> 
> And also.... maybe idle animation is too exagerated... I think you should go for something more "calm". 
> 
> 

Okai👌

**Comment by wilberquito** [comment]
@Jumalita  can you review  the new changes?

**Comment by Jumalita** [comment]
Ok!
I made few retouches on jump and land. Now jump ends and land starts in the same position. 

Just another thing...
When pork rolls... he needs to get back to attack, doesn't he?

Maybe i missed the animation that brings the enemy back to attack mode.
Let me know i am mistaken! 

@wilberquito

**Comment by wilberquito** [comment]
@Jumalita can you review the animations again?

**Comment by Jumalita** [comment]
Lovely! <3

**Pull request merged**
